baseURL = 'https://example.org/'
title = 'FIF UAQ'
theme = 'lugo'

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true
[languages]
[languages.es]
contentDir = 'content/es'
disabled = false
languageCode = 'es-MX'
languageDirection = 'ltr'
languageName = 'Español'
title = 'FIF UAQ'
weight = 1
[languages.en]
contentDir = 'content/en'
disabled = true
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = 'CS School UAQ'
weight = 2
